package es.vargontoc.pokemon.nuzlocker.domain.models.nuzlocke.enums;

public enum RuleReasonType { FIRST_ENCOUNTER, SHINY_CLAUSE, CATCHING_NOT_UNLOCKED, ZONE_ALREADY_USED, DUPLICATE_SPECIE, NO_ENCOUNTERS_IN_LOCATION, RUN_NOT_ACTIVE, NO_LEVEL_CAP, WITHIN_LEVEL_CAP, OVER_LEVEL_CAP, BATTLE_ITEMS_ALLOWED, BATTLE_ITEMS_FORBIDDEN }
